services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3309:3306
    networks:
      - app-networks
  api:
    # build:
    image: riqinho/study-apir:0.0.2
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - DB_SERVER=db
      - DB_PORT=3309
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - app-networks

networks:
  app-networks:
