name: Continuous Integration

on: 
    push

jobs:
    build_and_pull:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: acnaweb
                password: senha