name: Continuous Integration

on:
  push:
    branches:
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buil da Aplicação
        run: mvn clean package
