name: Continuous Integration

on:
  push:
    branches:
      - feature/**
      - realease
      - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build da Aplicação
        run: mvn clean package -DskipTests

      - name: Execução de Testes Unitários
        run: mvn test

      - name: Teste de criação de imagem
        run: docker build -t study-apir .
