on: 
    push

jobs:
    demo1: 
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello, World"
            - name: step2
              run:
                echo "Mensagem 2"
                echo "Mensagem 3"
                ls -la